blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/misterioso013/upack/discussions
    about: For general questions, ideas, and community discussions
  - name: 📖 Documentation
    url: https://github.com/misterioso013/upack/blob/main/docs/COMPLETE_GUIDE.md
    about: Check our complete guide before opening an issue
